### PR TITLE
Merge with readme from Altair

### PR DESCRIPTION
**Pull request by joelostblom**
This is my suggestion for how we can merge the roadmaps for the different projects. I have transferred over the content from https://altair-viz.github.io/about/roadmap.html and adapted it to be more general. I also added a few things based on what I see as 

I didn't have time to update with what we have merged recently in Altair. I can do that tomorrow, but feel free to highlight if there are things you think should not be on here, or things that are missing.

If we merge this, I can follow up by creating issues for the specific items on the project board, including some of those that we closed recently. I think I need more permissions to create labels and close issues, @domoritz could you grant me these?

We could also pin this repo on the org for more visibility.

### CODE REVIEW

**Review by mattijn — APPROVED** [review]
Really nice @joelostblom! 👍

**Review by jonmmease — APPROVED** [review]
lgtm. Thanks @joelostblom!

**Review by binste — APPROVED** [review]
LGTM too. Could be a crucial part for the application to have this unified roadmap, thank you Joel for doing this!

I've pinned this repo and added you as an admin for this repo. Once #10 is approved by everyone, we'll then all be owners of the Vega org so we no longer have to manage per-repo permissions.

**Comment by domoritz** [comment]
I feel #10 was the wrong link, no?

**Review by domoritz — COMMENTED** [review]
Hmm, I don't like that we have some roadmap items in issues/cards in a project and others in markdown. Would you be okay with moving to cards as well? We could have a separate board for Altair. 

I like cards/issues because they are easier to update, close, comment on, and reference.

**Comment by joelostblom** [comment]
Thanks for the reviews everyone!

> Hmm, I don't like that we have some roadmap items in issues/cards in a project and others in markdown. Would you be okay with moving to cards as well?

Yes, that's what I meant with my comment about creating issues but reading it again I see it's not that clear. I can go ahead and create the issues after we merged this and have a tag for "Vega-Altair` on the same project board. I think it is still beneficial to have this narrative in the markdown readme as it give a more welcoming overview to what the direction of the project is, so I would like to keep it in addition to creating the cards (but I can maybe reduce the content of the overview a bit and move more details to the cards? what do you think?).

**Comment by mattijn** [comment]
I prefer a list of items in markdown over cards😂🤷.

I don't think a board will help us in implementing the roadmap any sooner.

**Comment by domoritz** [comment]
I don't have strong opinions but like consistency. What I like about the cards is that they can have tags as well. 

Screenshot 2024-04-12 at 11 57 30

I don't like that you need to click into them to read them, though. 

So I'd be cool with just moving everything to markdown. Either way, this looks good and I let you decide what makes the most sense

**Review by domoritz — APPROVED** [review]

**Comment by mattijn** [comment]
Thanks for the explanation. True! I see some value in that. 

We have had _one_ overview issue in which I preferred there was something like an in-issue interactive overview. 

It was this issue https://github.com/vega/altair/discussions/2599 in which we referred to >30 issues, where we ended up using a custom mermaid diagram:

image.

Most of the issues here are open or done, and any status in-between are not so important to me.

I just notice we Altair is officially part of Vega now:

image

🥳

**Comment by joelostblom** [comment]
I like both the narrative, the overview, the clear labels, and the fact that we can easily see which issues are part of a current are of focus... I thought more about this and think I have a way to get most of the good stuff via a project board where each column is an areas of focus and its description contains the narrative / overview. I have started and it looks like this:

image

You can easily see which repo/project the issue belongs to and you can also do your own breakdowns via the filters if you want. I agree that I don't get much value of seeing what's "in progress" via a dedicated column, so I don't think we lose much by not seeing that here (and you can see it via linked PRs). We can choose whether newly implemented features stay on the board, I think it makes sense for a while to indicate what's done.

One thing I like about this is that it removes the unnecessary layer of creating separate issues in the Roadmap repo (we can still create cards for general areas that are not in a repo yet). We just have the issues that are created in the respective project and then organize the larger ones in this board. I think this also is easier to update and more helpful for us to see the actual issues. To be clear, we absolutely do NOT need to add every single issue here. Just some larger areas of focus. 

Two minor things I don't like is that we can't pin the sidebar for everyone, so some people might miss the (now shorter) intro in the readme in the sidebar. The other is that if we only have this project board and no repo, we can't pin it to the org which might reduce visibility. If we think these are important, we could always retain the "Roadmap" repo and just have a short readme, the same as what is in the proj description sidebar.

Let me know your thoughts, I'll keep working since it sounds like no one has too strong opinions as long as we get the material merged, but let me know if anyone is heavily opposed.

**Comment by mattijn** [comment]
Nice compromise @joelostblom! If we add the last url you included to the board in a new section at https://vega.github.io than I think it is visible enough?

**Comment by joelostblom** [comment]
Thank you! I have updated this PR to just contain a link to the new project board. I re-requested approvals since that change the original intent, but the information there is the same (see post above for details). We can chose to keep the repo to advertise the link or remove it and add the link as @mattijn suggested. I don't have a strong opinion.

@domoritz If there is anything left in https://github.com/vega/roadmap/issues that you think should be included, feel free to add it. I included everything that I had a good understanding of.

**Review by domoritz — APPROVED** [review]

**Review by binste — APPROVED** [review]
The project board is really nice, thank you @joelostblom! As you said, it's convenient that we can link the actual issues from all repos directly on the roadmap :)

**Comment by joelostblom** [comment]
Merging this to have it ready when submitting the application.

**Pull request merged**
